{% set name = "raster-tools" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/raster_tools-{{ version }}.tar.gz
  sha256: 35970cf36a118f0bb69d1adbe42fad1aeef88502ba502fa773c63b410c4e8807

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77
  run:
    - python >={{ python_min }}
    - affine
    - dask >=2025.1.0
    - dask-geopandas >=0.4.3
    - dask-image
    - fiona
    - geopandas
    - numba
    - numpy >=1.22
    - odc-geo
    - pandas
    - pyogrio
    - pyproj
    - rioxarray
    - rasterio
    - scipy
    - shapely >=2.0
    - xarray
    # Optional: install `netcdf4` and `cfgrib` alongside raster-tools to
    # enable `open_dataset` for .nc and .grib files.

test:
  imports:
    - raster_tools
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/UM-RMRS/raster_tools
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Tools for processing geospatial data
  dev_url: https://github.com/UM-RMRS/raster_tools

extra:
  recipe-maintainers:
    - fbunt
